import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto} from "next/font/google";
import "./globals.css";
import NavBar from "./Navbar";
import AuthProvider from "./auth/Provider";
// import GoogleAnalyticsScript from "@/GoogleAnalyticsScript";
// import localFont from "next/font/local"

// const poppins = localFont({
//   src: "../public/fonts/poppins-regular-webfont.wolf2",
//   variable: "--font--poppins"
// })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500"]
})

export const metadata: Metadata = {
  title: "Nextjs tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="winter" lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <AuthProvider>
        <NavBar></NavBar>
          <main className="p-5">
            {children}
          </main>
      </AuthProvider>
      </body>
    </html>
  );
}
